# Generated by Django 5.2.9 on 2025-12-08 23:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Bijvoorbeeld 'adian_julia' of een andere familienaam.", max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Naam die op de site wordt getoond. Leeg = gebruik code/keuze.', max_length=128)),
                ('is_free_family', models.BooleanField(default=False, help_text='Als dit aan staat, zijn reserveringen gratis.')),
                ('user', models.OneToOneField(blank=True, help_text='Account dat namens dit gezin kan reserveren.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(help_text='Laatste overnachtingsdatum (check-out is de volgende ochtend).', verbose_name='Einddatum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('is_free', models.BooleanField(default=False)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.family', verbose_name='Gein')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
